version: '3.9'

services:
  db:
    image: postgres:16-alpine

    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
    - POSTGRES_DB=devdb
    - POSTGRES_USER=devuser
    - POSTGRES_PASSWORD=devpass

  django:
    build:
      context: .
      tags:
        - todo-django

    command: sh -c "
      python manage.py retry_db &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

    ports:
      - 8000:8000

    volumes:
      - .:/app:z

    environment:
      - DJANGO_SECRET_KEY=supersecretpassword
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=devpass

    depends_on:
      - db
