# Generated by Django 5.0 on 2024-01-20 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
from django.apps.registry import Apps
from django.db.backends.postgresql.schema import DatabaseSchemaEditor


def create_initial_category(apps: Apps, schema_editor: DatabaseSchemaEditor) -> None:
    Category = apps.get_model("todo", "Category")
    Category.objects.get_or_create(id=1, name="None")


def reverse_create_initial_category(apps: Apps, schema_editor: DatabaseSchemaEditor) -> None:
    Category = apps.get_model("todo", "Category")
    Category.objects.get(id=1, name="None").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(1, "The 'name' field must contain at least 1 character.")])),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('todo', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1, "The 'todo' field must contain at least 1 character.")])),
                ('completed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.category')),
            ],
        ),
        migrations.RunPython(
            create_initial_category,  # type: ignore
            reverse_create_initial_category,  # type:ignore
        )
    ]
